### PR TITLE
Add macOS example for opening terminal

### PR DESCRIPTION
**Pull request by ameistad**
Resolves: #3

### CODE REVIEW

**Comment by aristidesfl** [comment]
This doesn't open terminal in current file folder, but in root folder.

**Comment by math2001** [comment]
And that's what it's meant to do...

**Comment by aristidesfl** [comment]
Is it possible to open in current view as well?

**Comment by linkhanfeng** [comment]
> Is it possible to open in current view as well?
      {
          "name": "Terminal",
          "cmd": ["open", "-a", "Terminal", "$cwd"],
          "platform": "osx"
      }
If iTerm:
      {
          "name": "iTerm",
          "cmd": ["open", "-a", "iTerm", "$cwd"],
          "platform": "osx"
      }
my macOs version: 10.13.6

**Comment by kud** [comment]
Thank you @linkhanfeng , helped me a lot to open it with iTerm :)

**Comment by math2001** [comment]
There were some conflicts, so I had to do a manual merge... I'm not sure if I can mark this PR as merged, so I'm going to manually close it. Thanks for the contribution @ameistad :hearts:

**Pull request closed without merging**
