### PR TITLE
Fix case-insensitive rename under Windows

### PR DESCRIPTION
**Pull request by jfcherng**
Under Windows, you cannot directly rename `foo` -> `Foo` because they are considered as the same.

Currently, if you try to rename `foo` to `Foo` with this plugin with `Yes. Overwrite` under Windows, `foo` is sent to trash and then nothing happens.

The purposed solution is `foo` -> `whatever_random_name` -> `Foo`.

Related issue: https://github.com/SublimeTextIssues/Core/issues/1201

### CODE REVIEW

**Comment by math2001** [comment]
Hey, yep that's a good idea to automate this, I remember doing this manually. I don't really have the time the manage this PR right now, I'm passing my HSC right now...

I'll be free from the 11 November, so I'll check this out then. Thanks for contributing 🙂

**Comment by jfcherng** [comment]
@math2001 Good luck :smiley:

**Comment by math2001** [comment]
I'm actually gonna merge this now, it looks good 🙂 

Thanks for taking the time to contribute :heart: :tada:

**Comment by jfcherng** [comment]
> I might just implement that really quickly later, or if you wanna submit another PR, let me know slightly_smiling_face

I am not going to implement it myself since I generally treat `1/(2^122)` ~ `10^-37` ~ `0`.

**Pull request merged**
