### PR TITLE
Multi file creation following the syntax in Issue #42

### PR DESCRIPTION
**Pull request by TheSecEng**
Issue [#42](https://github.com/math2001/FileManager/issues/42)

Create multiple files with the `New` Command.

`index.{css, html,js}`

All files get created and then the extension at the first index (css) gets focus.

### CODE REVIEW

**Comment by TheSecEng** [comment]
Come to think of it, I don’t think I accounted for if the person accidentally puts a space in the extension list. Will let you review for feedback

**Comment by math2001** [comment]
Hey, thanks a bunch for your contribution! I've just seen it, I'll review it now :slightly_smiling_face:

**Comment by math2001** [comment]
I think it'd be a good idea to move this to an external function, something like `expand_shell_brackets`. That would make it easier to think about, and easy to test. That's one thing that's very important with this feature, because, at least for me, it's very error prone.

I'm thinking having the function like this:

```python
def expand_shell_brackets(input_from_user):
    # some logic
    return list_of_paths_to_create
```

### The feature itself

Then, if we are going to use a regex, it doesn't add much complexity to compile it ahead of time (using `re.compile`). That means that we don't have to recompute the regex every time.

Looking at the code, here's what stands out to me:

- the user isn't be able to escape the curly brackets (what if the user wants to create the file `hello{world}`?)
- You're assuming that the `{asdf,asdf}` logic is always happening at the end. But that's could not be the case, for example, the user could expect `simple.{input,output}.test` to expand to `simple.input.test`, `simple.output.test`.
- a new view should be opened for *every* file that is created. Currently, only one file is opened (it's not in the loop), see line 40 and next.

So, considering there are fair few bugs in a feature that is quite critical, I'm quite reluctant to merge this right now :slightly_frowning_face:. 

I apologize for the quality of the codebase, it doesn't set a very good example. But, I see a way to implement this feature really neatly, so here's how I think we should do it.

### Testing

Testing is done absolutely horribly in FileManager. We should be using `UnitTesting` (the package). Currently, it requires you to have python installed. It's an easy fix, I'll do that now.

This is a very good case where test driven development is going to work really well. So, here's what I'm going to do:

- make FileManager work with UnitTesting
- push the changes, and you'll pull
- we are going to write the test function
- implement the function
- merge :tada: 

Can you tell me what you think?

**Comment by TheSecEng** [comment]
I think all of those are really valid points. I’ll pull the code when it’s ready, in the mean time, I’ll work on a much cleaner implementation of this, with better error check and consistency.

**Comment by TheSecEng** [comment]
After looking at this more, I don't believe regex would be the right approach, it could get complicated and a regex would be more error prone in my eyes. It would be better to iterate over the string and extract the values that way.

Below is based on the shell bracket expansion

### Code
-------------
```python

test_cases = [
    "fake/path/main.{js,html,css}",
    "fake/path/{index,account}.{html,php}",
    "fake/path/{index,account}.{html,php}",
    "fake/path/{index{1,2,3,4,5},test}.{html,php}",
    "fake/path/{index{1,2,3{a,b},4,5},test}.{html,php}",
    "fake/path/main.html"
]


def escape_shell_brackets(input_from_user, depth=0):
    list_of_paths_to_create = [""]
    while input_from_user:
        char = input_from_user[0]
        if depth and (char == ',' or char == '}'):
            return list_of_paths_to_create, input_from_user
        if char == '{':
            x = get_extension_group(input_from_user[1:], depth + 1)
            if x:
                list_of_paths_to_create, input_from_user = [
                    a + b for a in list_of_paths_to_create for b in x[0]], x[1]
                continue
        if char == '\\' and len(input_from_user) > 1:
            input_from_user, char = input_from_user[1:], char + \
                input_from_user[1]

        list_of_paths_to_create, input_from_user = [
            a + char for a in list_of_paths_to_create], input_from_user[1:]

    return list_of_paths_to_create, input_from_user


def get_extension_group(input_from_user, depth):
    extension_group, comma = [], False
    while input_from_user:
        extension, input_from_user = escape_shell_brackets(
            input_from_user, depth)
        if not input_from_user:
            break
        extension_group += extension

        if input_from_user[0] == '}':
            if comma:
                return extension_group, input_from_user[1:]
            return ['{' + a + '}' for a in extension_group], \
                input_from_user[1:]

        if input_from_user[0] == ',':
            comma, input_from_user = True, input_from_user[1:]

    return None


for s in test_cases:
    print "\n\t".join([s] + escape_shell_brackets(s)[0]) + "\n"
```


### Output
----------------
```
test_cases = [
    "fake/path/main.{js,html,css}",
    "fake/path/{index,account}.{html,php}",
    "fake/path/{index,account}.{html,php}",
    "fake/path/{index{1,2,3,4,5},test}.{html,php}",
    "fake/path/{index{1,2,3{a,b},4,5},test}.{html,php}",
    "fake/path/main.html"
]


def escape_shell_brackets(input_from_user, depth=0):
    list_of_paths_to_create = [""]
    while input_from_user:
        char = input_from_user[0]
        if depth and (char == ',' or char == '}'):
            return list_of_paths_to_create, input_from_user
        if char == '{':
            x = get_extension_group(input_from_user[1:], depth + 1)
            if x:
                list_of_paths_to_create, input_from_user = [
                    a + b for a in list_of_paths_to_create for b in x[0]], x[1]
                continue
        if char == '\\' and len(input_from_user) > 1:
            input_from_user, char = input_from_user[1:], char + \
                input_from_user[1]

        list_of_paths_to_create, input_from_user = [
            a + char for a in list_of_paths_to_create], input_from_user[1:]

    return list_of_paths_to_create, input_from_user


def get_extension_group(input_from_user, depth):
    extension_group, comma = [], False
    while input_from_user:
        extension, input_from_user = escape_shell_brackets(
            input_from_user, depth)
        if not input_from_user:
            break
        extension_group += extension

        if input_from_user[0] == '}':
            if comma:
                return extension_group, input_from_user[1:]
            return ['{' + a + '}' for a in extension_group], \
                input_from_user[1:]

        if input_from_user[0] == ',':
            comma, input_from_user = True, input_from_user[1:]

    return None


for s in test_cases:
    print "\n\t".join([s] + escape_shell_brackets(s)[0]) + "\n"
 fake/path/main.{js,html,css}
	fake/path/main.js
	fake/path/main.html
	fake/path/main.css

fake/path/{index,account}.{html,php}
	fake/path/index.html
	fake/path/index.php
	fake/path/account.html
	fake/path/account.php

fake/path/{index,account}.{html,php}
	fake/path/index.html
	fake/path/index.php
	fake/path/account.html
	fake/path/account.php

fake/path/{index{1,2,3,4,5},test}.{html,php}
	fake/path/index1.html
	fake/path/index1.php
	fake/path/index2.html
	fake/path/index2.php
	fake/path/index3.html
	fake/path/index3.php
	fake/path/index4.html
	fake/path/index4.php
	fake/path/index5.html
	fake/path/index5.php
	fake/path/test.html
	fake/path/test.php

fake/path/{index{1,2,3{a,b},4,5},test}.{html,php}
	fake/path/index1.html
	fake/path/index1.php
	fake/path/index2.html
	fake/path/index2.php
	fake/path/index3a.html
	fake/path/index3a.php
	fake/path/index3b.html
	fake/path/index3b.php
	fake/path/index4.html
	fake/path/index4.php
	fake/path/index5.html
	fake/path/index5.php
	fake/path/test.html
	fake/path/test.php

fake/path/main.html
	fake/path/main.html
```

**Comment by TheSecEng** [comment]
This doesn’t solve the problem if we want to allow {1..3} {3..1} type expansions. Might need to revisit and update.

**Comment by math2001** [comment]
> After looking at this more, I don't believe regex would be the right approach, it could get complicated and a regex would be more error prone in my eyes. It would be better to iterate over the string and extract the values that way.

I couldn't agree more.

Instead of putting the code in a comment, you can just push to your fork (on your branch), it will update this pull request and give us a nice diff to work off of. I pushed the changes so UnitTesting works nicely now.

## Tests

So, we should have a `tests/test_shell_expansion.py` file that should be run by `UnitTesting: Test current package`, and it should automatically check static inputs against outputs (ie. the test file should just make sure that we always get your `Output` section in your previous comment).

If you're not sure how to get that setup, there's an example in `tests/test_path_helper.py`, or just let me know :-)

## Code

About the code, first, congrats on getting the feature implemented! But I find it pretty complex. Why do we have a two functions which call each other? I get that we might need recursion because of nested brackets, but having these two "siblings" functions looks pretty confusing. I think it'd be better to have *one* recursive function, with maybe calls helpers around if needed (like parent-child style). Because when I read it, I think "alright I need to understand `get_extension_group`, but then you call `escape_shell_brackets` which just sends me in a loop where i have to keep track of two recursive functions, and that's harder than it needs to be.

Also, I think it would be clearer if we tried to do as little as possible on each line, ie:

```python
list_of_paths_to_create, input_from_user = [
                    a + b for a in list_of_paths_to_create for b in x[0]], x[1]

# split into

list_of_paths_to_create =  [a + b for a in list_of_paths_to_create for b in x[0]]
input_from_user = x[1]
```

It's not as fancy, but it's just so much easier to read.

Here are a few cases that don't work right now:

```
hello{a\b} should give helloab, but we get hello{a\b}
file\{name\} should give file{name} but gives file\{name\}
```

Cases we have to make sure we test, but that do currently work :+1:

```
file{name` should give `file{name` 
```

Note for later: once this is done, I think we will have to make sure that no users uses backslashes in their paths (instead of `/`). Because otherwise they might want to do something like this: `myfolder\{a,b}myfile.txt}` expecting `myfolder\amyfile.txt` and `myfolder\bmyfile.txt`. We could define some fancy rule like "you need to escape both it to be actually escape" but there would be some edge cases there too. Assuming (and hence documenting) that we expect only forward slashes is more logical (that's what 99% are probably doing anyway) and simpler.

For your algorithm, have you thought about trying to use a queue? I think it would lead to a cleaner implementation. Either that or *one* recursive function with simple helpers (the helpers would just be function that can do anything, but *not* call the parent, because that adds in a *lot* of complexity).

PS: this is the first time I'm on the "managing" side of a multi-step PR like this. So don't hesitate to tell me if you think I'm being too annoying or "using" you (I kind of feel bad just getting you to code up something and then tell you, "nah that's not clear enough for me, try again"), or doing anything in a non-optimal way. I feel like it can be a bit discouraging, and I don't wanna turn you away from FileManager 🙂 My mode of reasoning is just: "Is this code as easy to understand as it can be?" and "Will I be able to maintain this in 2 years without having to re-write the whole thing?". Right now I think that this is more complex than it needs to be. So, just don't hesitate to let me know how you feel, it will help me make sure I'm as nice and efficient as I can be :-)

**Comment by TheSecEng** [comment]
> Instead of putting the code in a comment, you can just push to your fork (on your branch), it will update this pull request and give us a nice diff to work off of. I pushed the changes so UnitTesting works nicely now.

I'll update my fork next time for easier review

> ## Tests
> So, we should have a `tests/test_shell_expansion.py` file that should be run by `UnitTesting: Test current package`, and it should automatically check static inputs against outputs (ie. the test file should just make sure that we always get your `Output` section in your previous comment).
> 
> If you're not sure how to get that setup, there's an example in `tests/test_path_helper.py`, or just let me know :-)
> 

Good point, now that you have the `tests` built out, I ensure my next commit includes true unit tests to avoid having to re-write a new test everytime.


> ## Code
> About the code, first, congrats on getting the feature implemented! But I find it pretty complex. Why do we have a two functions which call each other? I get that we might need recursion because of nested brackets, but having these two "siblings" functions looks pretty confusing. I think it'd be better to have _one_ recursive function, with maybe calls helpers around if needed (like parent-child style). Because when I read it, I think "alright I need to understand `get_extension_group`, but then you call `escape_shell_brackets` which just sends me in a loop where i have to keep track of two recursive functions, and that's harder than it needs to be.
> 
> Also, I think it would be clearer if we tried to do as little as possible on each line, ie:
> 
> ```python
> list_of_paths_to_create, input_from_user = [
>                     a + b for a in list_of_paths_to_create for b in x[0]], x[1]
> 
> # split into
> 
> list_of_paths_to_create =  [a + b for a in list_of_paths_to_create for b in x[0]]
> input_from_user = x[1]
> ```
> 
> It's not as fancy, but it's just so much easier to read.

I couldn't agree more, it look very messy as I wrote it, and it was late so I eventually got tired but wanted feedback. So....that is my fault, I'll ensure it's more clean and concise on the next iteration.

> Here are a few cases that don't work right now:
> 
> ```
> hello{a\b} should give helloab, but we get hello{a\b}
> file\{name\} should give file{name} but gives file\{name\}
> ```

Ahh, I see. We need to include proper `escaping`. **Noted**

> Cases we have to make sure we test, but that do currently work 👍
> 
> ```
> file{name` should give `file{name` 
> ```
> 
> Note for later: once this is done, I think we will have to make sure that no users uses backslashes in their paths (instead of `/`). Because otherwise they might want to do something like this: `myfolder\{a,b}myfile.txt}` expecting `myfolder\amyfile.txt` and `myfolder\bmyfile.txt`. We could define some fancy rule like "you need to escape both it to be actually escape" but there would be some edge cases there too. Assuming (and hence documenting) that we expect only forward slashes is more logical (that's what 99% are probably doing anyway) and simpler.
> 

Good point, I can see how this could get complicated quickly. Maybe I can look to see the code of how bash implements this. But that might just get to complicated for FileManagers use case.

> For your algorithm, have you thought about trying to use a queue? I think it would lead to a cleaner implementation. Either that or _one_ recursive function with simple helpers (the helpers would just be function that can do anything, but _not_ call the parent, because that adds in a _lot_ of complexity).
> 

I am not sure what you mean by a queue and how it would apply to this implementation. Care to expand on that? 

As for the helpers route, I can certainly re-write it to include a better flow.

> PS: this is the first time I'm on the "managing" side of a multi-step PR like this. So don't hesitate to tell me if you think I'm being too annoying or "using" you (I kind of feel bad just getting you to code up something and then tell you, "nah that's not clear enough for me, try again"), or doing anything in a non-optimal way. I feel like it can be a bit discouraging, and I don't wanna turn you away from FileManager 🙂 My mode of reasoning is just: "Is this code as easy to understand as it can be?" and "Will I be able to maintain this in 2 years without having to re-write the whole thing?". Right now I think that this is more complex than it needs to be. So, just don't hesitate to let me know how you feel, it will help me make sure I'm as nice and efficient as I can be :-)
> 

Not at all, I code on my free time and I am actually a Security Engineer by trait. So I enjoy the learning and seeing how others think. It helps me to get better.

**Comment by math2001** [comment]
> Maybe I can look to see the code of how bash implements this. But that might just get to complicated for FileManagers use case.

I looked at the results from bash vs fish, and I prefer fish's version (the only difference I noticed was that bash expand `{hello}` to `{hello}` whilst fish expands `{hello}` to `hello`).

> I am not sure what you mean by a queue and how it would apply to this implementation. Care to expand on that?

A queue is "first in first out" kind of list.

```python
>>> from collections import deque
>>> queue = deque(['initial'])
>>> queue.append('hello')
>>> queue.popleft()
'initial'
>>> queue.popleft()
'hello'
>>> 
```

You can think of it visually: the elements flow from the right (you add stuff to the right with `append`) to the left (you consume them with `popleft`). Note that you could definitely do this with a regular list, but it's [more efficient to use a `deque`](https://devdocs.io/python~3.7/library/collections#collections.deque)

```python
queue = deque(["original {user,input} {to,expand}"])

finished_expansions = []

while queue: # while there is stuff on the queue
    
    element = queue.popleft()

    # to a little bit of processing
    # eg. expand only one bracket, let's say the first one. In our case, we'd get something
    # like this:
    # elements_expanded = [
    #     "origin user {to,expand}",
    #     "original input {to,expand}"
    # ]

    # and that's where the magic happens
    for element in elements_expanded:
        if finished_expanding(element):
            finished_expansions.append(element)
        else:
            # there is still some stuff to process
            # so we add it back on the queue
            queue.append(element)
```

So you see that on the queue, you only have elements which are still left to process. This is almost like a recursive program (swap the `while ...:` for a `def func` and the `queue.append` with `func(...)`), and it's almost equivalent. Almost.

The one with the functions calls is *depth* first, whilst the one with the queue is *breadth* first. It has to do with the order they are going to process each element. Using the same input as above, here's the order in which the *depth* first one (so with the function calls) is going to process each expansion:

```
original {user,input} {to,expand}
original user {to,expand}
original user to
original user expand
original input {to,expand}
original input to
original input expand
```

Whilst the *breadth* first one (so with a queue), it would do this:

```
original {user,input} {to,expand}
original user {to,expand}
original input {to,expand}
original user to
original user expand
original input to
original input expand
```

Do you see the difference? The depth first search process the whole string and then goes to the next "branch" just "above", whilst the *breadth* first one advances each branch at the same time.

So, which one do we want in this case? Well, I think it doesn't really matter *in our case* because we want to explore *every* path anyway. One is more efficient than the other if it allows you to stop early. That's why when you're trying to find the shortest path between two points for example (and you can't just draw a straight line), you want to use *breadth* first search because it allows you to stop as soon as you find a solution (you know that this solution is the smallest one because you've advanced every "branch" equally). With a depth first search, if you were unlucky enough to pick the start of a very long path, you would explore that *entire* path before exploring another one.

Note that I've only started to properly think about this kind of stuff recently, so my understanding might be a bit erroneous, and it's definitely still growing (I just noticed this quasi equivalence just by writing this :slightly_smiling_face:). But I'm pretty confident that I haven't said anything outstandingly *wrong* here.

*The only thing I'm not to sure about right now is whether breadth first vs depths first actually doesn't matter when we start talking about nested brace expansions...

> hello{a\b} should give helloab, but we get hello{a\b}

Oops, that's actually a mistake, my bad. `hello{a\b}` should give `helloa\b` or an error (preferably an error), not `helloab`. We should only be allowed to escape `{` and `}`, and `,` within a `{}` pair.

> Not at all, I code on my free time and I am actually a Security Engineer by trait. So I enjoy the learning and seeing how others think. It helps me to get better.

Oh that's so great! I definitely "resonate" with that perspective :slightly_smiling_face: I would actually be really interested in talking to you about what your job's like, if you don't mind. I looked at your profile, but you don't seem to have a public email on there... If you've got a bit a time, I'd really appreciate it if we could have a quick chat (my email's <australie.p@gmail.com>). I'd completely undertand if you're busy though :slightly_smiling_face: 

Nonetheless, don't hesitate to tell me if I get a bit too annoying :wink:

**Comment by TheSecEng** [comment]
Thanks for such a thorough explanation. Dequeue looks amazing. I am going to work on seeing if I can get something going over the next week.

**Comment by TheSecEng** [comment]
Honestly, After multiple trials and errors, I think implementing this completely would be quite the task. Although, another sublime text user facelessuser already developed a great library for this.

https://github.com/facelessuser/bracex 

Thoughts on including this as the brace expansion solution?

**Comment by facelessuser** [comment]
@TheSecEng mentioned you guys were considering Bracex, so I thought I'd pop in and comment. Just an FYI, this solution actually has numerous test cases that are run through Bash and compared against our own implementation: https://github.com/facelessuser/bracex/blob/master/tests/brace-cases.txt. When I wrote it, it was after I searched long and hard for a suitable brace expander in Python.

100% Bash compatibility was not the goal, but I did try to follow very closely, and the known places it deviates were intentionally allowed. I'm not aware of a Python brace expander that follows as close as bracex does.

If you guys to run into an issue, or have questions about behavior, I'm more than happy to answer questions and fix relevant issues in the library. Bracex doesn't currently have much outside usage except indirectly through a number of my own projects, so I'm interested to get feedback. No worries if you guys decide on a different solution in the end, you won't hurt my feelings, I'm more just interested in capturing general issues maybe I didn't consider in order to improve the library.

**Comment by TheSecEng** [comment]
@math2001 Hey bud! Any update on this?

**Comment by facelessuser** [comment]
@TheSecEng is anyone providing the braces dependency in Package Control?

**Comment by TheSecEng** [comment]
> @TheSecEng is anyone providing the braces dependency in Package Control?

Good point forgot to double check. Thoughts on making a PR on PC or including bracex in the repo at the `lib` directory.

**Comment by facelessuser** [comment]
You can go either way. Putting it at as a dependency on PC makes it available to other packages. Vendoring it locally means you always control the version you are using. Both have their advantage.

**Comment by TheSecEng** [comment]
https://github.com/wbond/package_control_channel/pull/7855

**Comment by TheSecEng** [comment]
Closing in favor of an upcoming PR

**Pull request closed without merging**
