### PR TITLE
Use WindowCommands to reduce some hazzle

### PR DESCRIPTION
**Pull request by deathaxe**
FileManager shouldn't abuse the ApplicationCommand class but use the WindowCommand which is designed to be used for window related commands.

By doing so some of the hazzle in the different commands used to retrieve the active window and/or file can be omitted.

It helps to make the commands a bit more pythonic.

Note:

1. This commit is a suggestion and may some review/improvements before merging.
2. It may break compatibility with Sublime Text 2.
3. There may be some more things to improve.

### CODE REVIEW

**Comment by TerminalFi** [comment]
@deathaxe Level of concern that these are breaking changes?

**Comment by deathaxe** [comment]
Command names haven't changed, so bidnings should not be effected. Some menus are reoraganized. Shouldn't be a big deal however. I have been using that branch since opening this PR without noticing any issues.

**Comment by TerminalFi** [comment]
@math2001 Any chances of this getting merged? I have a PR I want to opens that depends on this

**Comment by deathaxe** [comment]
@math2001: In case you are no longer interested, feel free to transfer the repo to https://github.com/SublimeText org, so community can continue maintaining it.

**Comment by math2001** [comment]
Yes I think I'll have to transfer it over at some point.

> I have been using that branch since opening this PR without noticing any issues.

:+1: I'll merge this soon then

**Comment by math2001** [comment]
> This commit is a suggestion and may some review/improvements before merging.

Arg I forgot about that, that's probably why i never got around to merging.

I blindly trusted everything was good. It introduced at least few bugs: 40c452353384566da275ae9a4b73692385d3413f dce16b555952da7434b4e887e032f64f34431e1e

**Comment by math2001** [comment]
I'll keep using it for a bit and i'll tag it after a few days so that every one gets the update

**Pull request merged**
