### PR TITLE
Normalize names of the context menu items

### PR DESCRIPTION
**Pull request by ihodev**
Change context menu items' case to be the same as in the main ST's menu.

### CODE REVIEW

**Comment by math2001** [comment]
Thanks! Those kind of things aren't my strong point in English 😄

**Comment by ihodev** [comment]
The same story) Thanks a lot :wink: P.S. I like this plugin very much, it's simple, hackable, clean & provides everything that I need in the sidebar)

**Comment by math2001** [comment]
I'm so pleased to hear that you like this plugin! Yes, the point of this plugin was to be simple, to only provided the **needed** options 😄 

Thank you very much for your feedback and your participation, it's really "rewarding". Just in case, have you had a look at [the wiki](https://github.com/math2001/FileManager/wiki)? There's plenty of things that you might want to know 😉

**Comment by ihodev** [comment]
Yes, I've read the wiki. I enjoy almost all features)

**Comment by math2001** [comment]
What feature do you *not* enjoy?

**Comment by ihodev** [comment]
I'm always trying to simplify my workflow. Advanced file creation (deep nesting & templates) is not for me, it works good, but I use it very rarely)

**Comment by math2001** [comment]
Ok, I'll remember. Here's how I use them: I use template for very small things. For example:

```python
# -*- encoding: utf-8 -*-


```
```js
"use strict";


```

I use deep nesting when I create style sheet especially: `styles/css/my_stylesheet.css`. But, the gain of time  compared to using the mouse can be discussed (even with the auto completion), but I'm learning VIM, so I try to use the mouse as less as possible. 😄

**Pull request merged**
